name: airfryer_recipes
description: A comprehensive Flutter-based Airfryer Recipe mobile app with modern UI, recipe management, and meal planning features.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  provider: ^6.0.5
  sqflite: ^2.2.8+4
  path: ^1.8.3
  http: ^0.13.6
  shared_preferences: ^2.1.1
  cached_network_image: ^3.2.3
  flutter_svg: ^2.0.5
  intl: ^0.18.1
  path_provider: ^2.0.15
  flutter_local_notifications: ^14.1.1
  uuid: ^3.0.7
  url_launcher: ^6.1.11
  flutter_rating_bar: ^4.0.1
  flutter_staggered_grid_view: ^0.6.2
  loading_animation_widget: ^1.2.0+4
  font_awesome_flutter: ^10.4.0
  carousel_slider: ^4.2.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1
  animations: ^2.0.7
  flutter_slidable: ^3.0.0
  table_calendar: ^3.0.9
  lottie: ^2.4.0
  image_picker: ^0.8.7+5
  flutter_html: ^3.0.0-beta.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
